language: java

sudo: false

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov
  
install: true

script:
  - mvn test -B

after_script:
  - codecov
